# render.yaml
services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      environment:
        PYTHON_VERSION: 3.9.18
